# SPDX-License-Identifier: MIT OR Apache-2.0

services:
  floresta:
    container_name: floresta
    build:
      context: ../..
      dockerfile: contrib/docker/Dockerfile
      args:
        BUILD_FEATURES: "metrics"
    command: >-
      florestad --data-dir /data/.floresta
      -n ${NETWORK:-bitcoin}
      --rpc-address 0.0.0.0:${RPC_PORT:-8332}
      --electrum-address 0.0.0.0:${ELECTRUM_PORT:-50001}
    ports:
      - ${RPC_PORT:-8332}:${RPC_PORT:-8332}
      - ${ELECTRUM_PORT:-50001}:${ELECTRUM_PORT:-50001}
      - 3333:3333
    tty: true
    restart: unless-stopped
    volumes:
      - ${FLORESTA_DATA:-floresta_data}:/data/.floresta
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ../../crates/floresta-metrics/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ../../crates/floresta-metrics/grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

volumes:
  floresta_data:
    name: floresta_data
  prometheus_data:
    name: prometheus_data
  grafana_data:
    name: grafana_data
