[package]
name = "floresta-compact-filters"
version = "0.5.0"
authors = ["Floresta Developers <contact@getfloresta.org>"]
rust-version.workspace = true
edition.workspace = true
repository = "https://github.com/davidson-souza/floresta"
description = """
BIP158 compact filters for easy rescan of the blockchain in light clients.
"""
readme.workspace = true # Floresta/README.md
license.workspace = true

[dependencies]
bitcoin = { workspace = true }

# Local dependencies
floresta-chain = { workspace = true }

[lints]
workspace = true
