# SPDX-License-Identifier: MIT OR Apache-2.0

name: Benchmarks

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
permissions: {}

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install 1.85.0 Rust Toolchain
        run: |
          rustup toolchain install 1.85.0 --profile minimal --no-self-update
          rustup default 1.85.0

        # Bi-weekly numbers to refresh caches every two weeks, ensuring recent project changes are cached
      - name: Set bi-weekly cache key
        # Use '10#' to always treat week number as base-10 (avoids octal when number has a leading zero)
        run: |
          YEAR=$(date +%Y)
          WEEK=$(date +%U)
          BIWEEK=$(( (10#$WEEK + 1) / 2 ))
          echo "CACHE_VERSION=${YEAR}(${BIWEEK})" >> $GITHUB_ENV

          # Hash of all files that could affect the build
          echo "BUILD_HASH=${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}" >> $GITHUB_ENV
        shell: bash

      # Restore Rust build cache and artifacts
      - name: Restore Rust cache
        id: cache
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/release/
          # Cache key depends on the bi-week we are on (cache version)
          key: ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-${{ env.BUILD_HASH }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ env.CACHE_VERSION }}-
            ${{ runner.os }}-cargo-

      # Run benchmarks
      - name: Run cargo bench
        run: |
          cargo bench --package floresta-chain --no-default-features --features test-utils,flat-chainstore

      # Save cache only if the previous steps succeeded and there was not an exact cache key match
      # This happens everytime we modify any `cargo.lock` or `cargo.toml`, or each two weeks (caching recent changes)
      - name: Save Rust cache
        if: success() && steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/release/
          key: ${{ steps.cache.outputs.cache-primary-key }}

      # Store benchmark results
      - name: Store benchmark results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: benchmark-results
          path: target/criterion
